fail_fast: true

default_language_version:
  python: python3.12

repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml"]
    additional_dependencies: ["bandit[toml]"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
  - id: ruff-format
    name: ruff format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    language: system
    exclude: '^tests/'

- repo: https://github.com/pdm-project/pdm
  rev: 2.16.1
  hooks:
  - id: pdm-lock-check
    name: pdm lock check
  - id: pdm-export
    name: pdm export
    args: ['-o', 'requirements.txt', '--prod', '--without-hashes']
    files: ^pdm.lock$
    always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
    name: check large files
    args: ['--maxkb=1024']
  - id: check-toml
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
    name: fix eof newline
    types_or: [python, yaml, toml]
  - id: name-tests-test
    name: pytest filenames
    args: ['--pytest-test-first']
  - id: no-commit-to-branch
    name: forbid master
