services:

  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - 80:8000
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/dataservices
