name: mediary
services:
  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile.slim_uv
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - 80:8000
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - db
    volumes:
      - ./mediary/app:/mediary/app
      - ./mediary/config:/mediary/config
      - ./mediary/alembic:/alembic
  db:
    container_name: postgres
    build:
      dockerfile: dockerfiles/db/Dockerfile.alpine_uv
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/dataservices
