name: mediary
services:
  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - 80:8000
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - db
    volumes:
      - ./mediary/app:/home/mediary/app
      - ./mediary/settings:/home/mediary/settings
      - ./mediary/alembic:/home/mediary/alembic
  db:
    container_name: postgres
    build:
      dockerfile: dockerfiles/db/Dockerfile.alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/dataservices
