services:
  api:
    container_name: mediary-api
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    container_name: mediary-db
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data
