services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
